title = "Website Title"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 20

  [[menu.main]]
    identifier = "traening"
    name = "Træning"
    url = "/traening"
    weight = 10
  
    [[menu.main]]
    identifier = "oevelser"
    name = "Øvelser"
    url = "/traening/oevelser"
    parent = "traening"
    weight = 10

    [[menu.main]]
    identifier = "programmer"
    name = "Programmer"
    url = "/traening/programmer"
    parent = "traening"
    weight = 10
