title = "Website Title"

[menu]
  [[menu.main]]
    identifier = "oevelser"
    name = "Øvelser"
    url = "/oevelser"
    weight = 1
  [[menu.main]]
    identifier = "programmer"
    name = "Programmer"
    url = "/programmer"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3